In [1]:
import numpy as np

In [2]:
ar = np.arange(3, 32)

In [3]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

np.any
np.all
np.where

In [13]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x` and `y` need to have the same
        shape as `condition`.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are 1-D, `wh

In [14]:
np.where(ar <10, 15, 18)

array([15, 15, 15, 15, 15, 15, 15, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18])

In [22]:
np.any([0, 1, 1, 1, 0])

True

In [26]:
np.any([False, True, False, True, True])

True

In [27]:
np.any([[True,False], [True, False]])

True

In [28]:
np.any([[True,False], [True, False]], axis=1)

array([ True,  True], dtype=bool)

In [29]:
np.any([[True,False], [True, False]], axis=0)

array([ True, False], dtype=bool)

In [30]:
(2, 3, 3)

(2, 3, 3)

In [31]:
np.all([[True, False], [True, False]])

False

In [32]:
np.all([[True, False], [True, False]], axis=0)

array([ True, False], dtype=bool)

In [33]:
np.all([[True, False], [True, False]], axis=1)

array([False, False], dtype=bool)

In [34]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [35]:
ar.sum()

493

In [36]:
ar.max()

31

In [37]:
ar.min()

3

In [39]:
ar.cumsum()

array([  3,   7,  12,  18,  25,  33,  42,  52,  63,  75,  88, 102, 117,
       133, 150, 168, 187, 207, 228, 250, 273, 297, 322, 348, 375, 403,
       432, 462, 493], dtype=int32)

In [40]:
ar.size

29

In [42]:
ar2 = np.arange(0, 12).reshape(3,4)

In [43]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
ar2.sum()

66

In [45]:
ar2.sum(axis=1)

array([ 6, 22, 38])

In [46]:
ar2.sum(axis=0)

array([12, 15, 18, 21])

In [47]:
ar3 = np.arange(0, 12). reshape(2, 2, 3)

In [48]:
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
ar3.sum(axis=0)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [50]:
ar3.sum(axis=1)

array([[ 3,  5,  7],
       [15, 17, 19]])

In [51]:
ar3.sum(axis=2)

array([[ 3, 12],
       [21, 30]])

In [54]:
ar4 =np.arange(0, 16).reshape(2, 2, 2, 2)

In [55]:
ar4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [56]:
ar4.sum(axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [57]:
ar4.sum(axis=1)

array([[[ 4,  6],
        [ 8, 10]],

       [[20, 22],
        [24, 26]]])

In [58]:
ar5 = np.arange(0, 24).reshape((2, 3, 4))

In [59]:
ar5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
ar5.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [62]:
ar5.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [63]:
ar5.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [65]:
ar6 = np.arange(0, 120).reshape((2, 3, 4, 5))

In [66]:
ar6

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [67]:
ar6.sum(axis=0)

array([[[ 60,  62,  64,  66,  68],
        [ 70,  72,  74,  76,  78],
        [ 80,  82,  84,  86,  88],
        [ 90,  92,  94,  96,  98]],

       [[100, 102, 104, 106, 108],
        [110, 112, 114, 116, 118],
        [120, 122, 124, 126, 128],
        [130, 132, 134, 136, 138]],

       [[140, 142, 144, 146, 148],
        [150, 152, 154, 156, 158],
        [160, 162, 164, 166, 168],
        [170, 172, 174, 176, 178]]])

In [68]:
ar6.sum(axis=1)

array([[[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[240, 243, 246, 249, 252],
        [255, 258, 261, 264, 267],
        [270, 273, 276, 279, 282],
        [285, 288, 291, 294, 297]]])

In [72]:
ar6.sum(axis=1).shape

(2, 4, 5)

In [69]:
ar6.sum(axis=2)

array([[[ 30,  34,  38,  42,  46],
        [110, 114, 118, 122, 126],
        [190, 194, 198, 202, 206]],

       [[270, 274, 278, 282, 286],
        [350, 354, 358, 362, 366],
        [430, 434, 438, 442, 446]]])

In [70]:
ar6.sum(axis=3)

array([[[ 10,  35,  60,  85],
        [110, 135, 160, 185],
        [210, 235, 260, 285]],

       [[310, 335, 360, 385],
        [410, 435, 460, 485],
        [510, 535, 560, 585]]])

In [73]:
ar6.sum(axis=3).shape

(2, 3, 4)