# datascience

- Numpy "numeric processing library"

In [1]:
[1, 2 ,3 ,4]

[1, 2, 3, 4]

In [2]:
import array

In [8]:
array.array ('i', [1, 2, 3, 4])

array('i', [1, 2, 3, 4])

In [6]:
[1, 'a']

[1, 'a']

In [9]:
array.array('i',  [1, 'a'])

TypeError: an integer is required (got type str)

In [10]:
import numpy as np

In [11]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [12]:
lst = [1, 2, 3, 4]

In [13]:
nplst = np.array(lst)

In [15]:
type(lst)

list

In [16]:
type(nplst)

numpy.ndarray

In [17]:
nplst

array([1, 2, 3, 4])

In [18]:
nplst.dtype

dtype('int32')

In [20]:
np.array([1, 2, 3])

array([1, 2, 3])

In [21]:
np.array([1, 2, 3.0])

array([ 1.,  2.,  3.])

In [22]:
np.array([1, 2,3.0]).dtype

dtype('float64')

In [23]:
np.array([1, 2,'3'])

array(['1', '2', '3'], 
      dtype='<U11')

In [24]:
nplst

array([1, 2, 3, 4])

In [25]:
lst

[1, 2, 3, 4]

In [26]:
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [27]:
nplst * 2

array([2, 4, 6, 8])

In [28]:
lst / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [29]:
nplst/ 2

array([ 0.5,  1. ,  1.5,  2. ])

In [30]:
nplst

array([1, 2, 3, 4])

In [31]:
dir(nplst)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [32]:
nplst

array([1, 2, 3, 4])

In [33]:
nplst.shape

(4,)

In [34]:
nplst.ndim

1

In [35]:
nplst.nbytes

16

In [36]:
nplst.size

4

In [38]:
nplst.nbytes * nplst.size

64

In [39]:
range(0, 12)

range(0, 12)

In [42]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
tw = np.arange(0,12)

In [44]:
tw

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
tw.shape

(12,)

In [46]:
tw.ndim

1

In [47]:
tw.reshape([4, 3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
np.array([1, 2, 3])

array([1, 2, 3])

In [50]:
np.array([[1, 2], [1, 2]])

array([[1, 2],
       [1, 2]])

In [51]:
help(tw.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function



In [52]:
np.array([[1, 2], [1, 2, 3]])

array([[1, 2], [1, 2, 3]], dtype=object)

In [53]:
np.array([[1, 2], [1, 2]])

array([[1, 2],
       [1, 2]])

In [54]:
tw

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
tw.reshape([2, 2, 3])

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [58]:
np.arange(0, 16).reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])